spring:
  http.encoding.charset: UTF-8
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDB10Dialect
  flyway:
    locations: classpath:db/migrations/

security:
  tokenPrefix: "Bearer "
  headerString: "Authorization"

datasource:
  hovy:
    jdbcUrl: jdbc:mysql://localhost/hovy?useSSL=false
    driverClassName: org.mariadb.jdbc.Driver
    maximumPoolSize: 10
    dataSourceProperties:
      cachePrepStmts: true
      useServerPrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
